<?php
use Symfony\Component\HttpFoundation\RedirectResponse;

function product_list_theme(){
    return array(
       "product_list" => array(
           'variables' =>  array
            (
               "params" => [],
               "title" =>   "this is title comming from sample_api dot module file",
            )
        )
    );


}
// function product_list_preprocess_page(&$variables) {
//     $user = \Drupal::currentUser()->isAnonymous();
//     $path = \Drupal::service('path.matcher')->isFrontPage();
//     if($path && $user){
//         $response = new RedirectResponse("/home");
//         $response->send();
//     }
// }



// function opigno_custom_updates_preprocess_page(&$variables) {
//     $user = \Drupal::currentUser()->isAnonymous();
//     $path = \Drupal::service('path.matcher')->isFrontPage();
//     if($path && $use){
//         $response = new RedirectResponse("/home");
//         $response->send();
//     }
// }
